""" list of additional sample test parameters that are included
    as testapp configparser defaults
    """
incl_list = [
['quicktest', 'param-agentsize', '4'],
['quicktest', 'param-barriertype', '0'],
['quicktest', 'param-challenge', '5'],
['quicktest', 'param-chooseparentsbyfitness', 'true'],
['quicktest', 'param-deletionratio', '0.5'],
['quicktest', 'param-displaysamplegenomes', '1'],
['quicktest', 'param-displayscale', '8'],
['quicktest', 'param-geneinsertiondeletionrate', '0.0'],
['quicktest', 'param-genomeanalysisstride', '100'],
['quicktest', 'param-genomecomparisonmethod', '1'],
['quicktest', 'param-genomeinitiallengthmax', '64'],
['quicktest', 'param-genomeinitiallengthmin', '64'],
['quicktest', 'param-genomemaxlength', '300'],
['quicktest', 'param-imagedir', 'images'],
['quicktest', 'param-killenable', 'false'],
['quicktest', 'param-logdir', 'logs'],
['quicktest', 'param-longprobedistance', '24'],
['quicktest', 'param-maxgenerations', '101'],
['quicktest', 'param-maxnumberneurons', '8'],
['quicktest', 'param-numthreads', '4'],
['quicktest', 'param-pointmutationrate', '0.001'],
['quicktest', 'param-population', '1000'],
['quicktest', 'param-populationsensorradius', '2.5'],
['quicktest', 'param-responsivenesscurvekfactor', '2'],
['quicktest', 'param-savevideo', 'true'],
['quicktest', 'param-sexualreproduction', 'true'],
['quicktest', 'param-shortprobebarrierdistance', '4'],
['quicktest', 'param-signallayers', '1'],
['quicktest', 'param-signalsensorradius', '2.0'],
['quicktest', 'param-sizex', '64'],
['quicktest', 'param-sizey', '64'],
['quicktest', 'param-stepspergeneration', '300'],
['quicktest', 'param-updategraphlog', 'false'],
['quicktest', 'param-updategraphlogstride', 'videoStride'],
['quicktest', 'param-videosavefirstframes', '0'],
['quicktest', 'param-videostride', '100']
]
