name: docker

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    name: compile with docker
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build
        run: |
          docker build -t biosim4 .

      - name: compile
        run: |
          docker run --rm \
            -v `pwd`:/app \
            --user `id -u`:`id -g` \
            --name biosim biosim4 make
